FROM php:8.2.4-fpm-alpine3.16

#create regular user
RUN addgroup --gid 1000 regularuser
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "$(pwd)" \
    --ingroup "regularuser" \
    --no-create-home \
    --uid "1000" \
    "regularuser"

RUN apk update && apk add git libpng-dev libxml2-dev
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN apk add git libzip-dev zip \
  && docker-php-ext-install zip

RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install gd
RUN docker-php-ext-install soap
RUN docker-php-ext-install calendar
RUN docker-php-ext-install bcmath

# install redis extension
RUN apk --no-cache add pcre-dev ${PHPIZE_DEPS}
RUN pecl install -o -f redis
RUN docker-php-ext-enable redis

# added 9.12.2022 because of errors while building docker containers
RUN apk add --update linux-headers
# for development
RUN apk add --no-cache $PHPIZE_DEPS && pecl install xdebug && docker-php-ext-enable xdebug


COPY . /var/www/dbdiff/

COPY docker/init.sh /run/init.sh
RUN chmod +x /run/init.sh

## xdebug profile setup
RUN mkdir /opt/xdebug-profile
RUN chown www-data:www-data -R /opt/xdebug-profile


WORKDIR /var/www/dbdiff
CMD ["/run/init.sh"]

# Configure a healthcheck to validate that everything is up&running
#HEALTHCHECK --timeout=10s CMD curl --silent --fail php:9000/fpm-ping
